/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is generated by `next build` / `next dev`.
// see https://nextjs.org/docs/app/api-reference/config/typescript
